### ISSUE TITLE
Scenes does not start anymore

### ISSUE THREAD

**Issue by ThisBen** [ioBroker/ioBroker.scenes#27]
Log excerpt: 

`
2018-09-06 19:06:59.556	info	Restart adapter system.adapter.scenes.0 because enabled
2018-09-06 19:06:59.556	error	instance system.adapter.scenes.0 terminated with code 0 (OK)
2018-09-06 19:06:59.556	error	Caught by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
2018-09-06 19:06:59.556	error	Caught by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2018-09-06 19:06:59.556	error	Caught by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:345:8)
2018-09-06 19:06:59.556	error	Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
2018-09-06 19:06:59.555	error	Caught by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
2018-09-06 19:06:59.555	error	Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:244:12)
2018-09-06 19:06:59.555	error	Caught by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:319:9)
2018-09-06 19:06:59.555	error	Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1462:35)
2018-09-06 19:06:59.555	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1582:21
2018-09-06 19:06:59.554	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.scenes/main.js:613:57
2018-09-06 19:06:59.554	error	Caught by controller[0]: TypeError: Cannot set property 'actual' of null
scenes.0	2018-09-06 19:06:59.006	error	TypeError: Cannot set property 'actual' of null at /opt/iobroker/node_modules/iobroker.scenes/main.js:613:57 at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1582:21 at
scenes.0	2018-09-06 19:06:59.004	error	uncaught exception: Cannot set property 'actual' of null
`

Versions around ioBroker: 

admin 3.5.7
scenes 1.0.2
javascript 3.6.4

Node 6.12.0
npm 3.10.10

ioBroker.js-controller 1.4.2

**Comment by GermanBluefox** [comment]
Fixed in 2.0.1
