### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Pmant** [ioBroker/ioBroker.scenes#3]
Adapter stürzt ab als ich versucht habe Objekte einer Szene zu ändern.
```
host-raspberrypi	2015-08-09 08:48:19	error	instance system.adapter.scenes.0 terminated with code 6 (uncaught exception)
TypeError:	2015-08-09 08:48:19	error	at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
TypeError:	2015-08-09 08:48:19	error	at timer._onTimeout (timers.js:210:16)
TypeError:	2015-08-09 08:48:19	error	at null. (/opt/iobroker/node_modules/iobroker.scenes/main.js:345:43)
TypeError:	2015-08-09 08:48:19	error	Cannot read property 'length' of undefined
uncaught	2015-08-09 08:48:18	error	exception: Cannot read property 'length' of undefined
```

**Comment by GermanBluefox** [comment]
Ist jetzt gefixt. Und ist auf NPM.
"npm install scenes"

2015-08-09 8:51 GMT+02:00 Pmant <notifications@github.com>:
