### ISSUE TITLE
Kein Update möglich von 2.4.2 auf 3.0.4

### ISSUE THREAD

**Issue by Stormbringer11** [ioBroker/ioBroker.scenes#335]
Hallo,

leider läuft der Adapter nicht mehr wenn man ihn updaten will. Vorher hatte ich damit aber nie Probleme.

JS Controller 5.0.19
npm 10.7.0
node 18.20.3
Ubuntu 22.04.4

Im Log kommt und Adapter bleibt rot:

```	
2024-06-14 13:18:35.302	info	Send notification "system.restartLoop" to "telegram.1"
host.io-frost-prox
	2024-06-14 13:18:35.289	warn	Do not restart adapter system.adapter.scenes.0 because restart loop detected
host.io-frost-prox
	2024-06-14 13:18:35.289	info	Restart adapter system.adapter.scenes.0 because enabled
host.io-frost-prox
	2024-06-14 13:18:35.289	error	instance system.adapter.scenes.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11)
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23)
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2319:16)
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: at new Promise (<anonymous>)
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2320:16
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9564:19)
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:254:19)
host.io-frost-prox
	2024-06-14 13:18:35.289	error	Caught by controller[1]: Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
host.io-frost-prox
	2024-06-14 13:18:35.288	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
scenes.0
	2024-06-14 13:18:34.606	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
scenes.0
	2024-06-14 13:18:34.606	info	terminating
scenes.0
	2024-06-14 13:18:34.599	error	Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
scenes.0
	2024-06-14 13:18:34.598	error	Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:254:19) at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9564:19) at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2320:16 at new Promise (<anonymous>) at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2319:16) at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23) at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)
scenes.0
	2024-06-14 13:18:34.478	error	unhandled promise rejection: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
scenes.0
	2024-06-14 13:18:34.477	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
scenes.0
	2024-06-14 13:18:34.214	info	starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.scenes, node: v18.20.3, js-controller: 5.0.19
host.io-frost-prox
	2024-06-14 13:18:31.557	info	instance system.adapter.scenes.0 started with pid 2975408
host.io-frost-prox
	2024-06-14 13:18:30.329	info	Restart adapter system.adapter.scenes.0 because enabled
host.io-frost-prox
	2024-06-14 13:18:30.329	error	instance system.adapter.scenes.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11)
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23)
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2319:16)
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: at new Promise (<anonymous>)
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2320:16
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9564:19)
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:254:19)
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[1]: Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
host.io-frost-prox
	2024-06-14 13:18:30.329	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
scenes.0
	2024-06-14 13:18:29.639	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
scenes.0
	2024-06-14 13:18:29.638	info	terminating
scenes.0
	2024-06-14 13:18:29.630	error	Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
scenes.0
	2024-06-14 13:18:29.629	error	Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:254:19) at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9564:19) at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2320:16 at new Promise (<anonymous>) at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2319:16) at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23) at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)
scenes.0
	2024-06-14 13:18:29.509	error	unhandled promise rejection: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
scenes.0
	2024-06-14 13:18:29.508	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
scenes.0
	2024-06-14 13:18:29.177	info	starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.scenes, node: v18.20.3, js-controller: 5.0.19
host.io-frost-prox
	2024-06-14 13:18:26.195	info	instance system.adapter.scenes.0 started with pid 2975391
host.io-frost-prox
	2024-06-14 13:18:24.855	info	Restart adapter system.adapter.scenes.0 because enabled
host.io-frost-prox
	2024-06-14 13:18:24.855	error	instance system.adapter.scenes.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11)
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23)
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2319:16)
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: at new Promise (<anonymous>)
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2320:16
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9564:19)
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:254:19)
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[1]: Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
host.io-frost-prox
	2024-06-14 13:18:24.855	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
scenes.0
	2024-06-14 13:18:24.183	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
scenes.0
	2024-06-14 13:18:24.183	info	terminating
scenes.0
	2024-06-14 13:18:24.175	error	Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
scenes.0
	2024-06-14 13:18:24.175	error	Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:254:19) at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9564:19) at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2320:16 at new Promise (<anonymous>) at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2319:16) at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23) at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)
scenes.0
	2024-06-14 13:18:24.037	error	unhandled promise rejection: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
scenes.0
	2024-06-14 13:18:24.037	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
scenes.0
	2024-06-14 13:18:23.672	info	starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.scenes, node: v18.20.3, js-controller: 5.0.19
```

**Comment by netsensation** [comment]
Habe das selbe Problem

Alles Versionen nach 2.4.2 funktionieren nicht

**Comment by hanan070893** [comment]
Ich habe Version 2.3.9. Mache ich ein Update, ist der Adapter rot.
`scenes.0
2024-06-23 13:12:49.844	info	starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.scenes, node: v20.15.0, js-controller: 5.0.19

scenes.0
2024-06-23 13:12:41.270	info	terminating

scenes.0
2024-06-23 13:12:40.769	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

scenes.0
2024-06-23 13:12:40.769	info	terminating

scenes.0
2024-06-23 13:12:40.765	error	Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed

scenes.0
2024-06-23 13:12:40.765	error	Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:254:19) at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9564:19) at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2320:16 at new Promise (<anonymous>) at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2319:16) at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23) at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)

scenes.0
2024-06-23 13:12:40.680	error	unhandled promise rejection: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed

scenes.0
2024-06-23 13:12:40.680	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

scenes.0
2024-06-23 13:12:40.630	info	starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.scenes, node: v20.15.0, js-controller: 5.0.19

scenes.0
2024-06-23 13:12:10.167	info	terminating

scenes.0
2024-06-23 13:12:09.667	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

scenes.0
2024-06-23 13:12:09.666	info	terminating

scenes.0
2024-06-23 13:12:09.662	error	Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed

scenes.0
2024-06-23 13:12:09.662	error	Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:254:19) at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9564:19) at /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2320:16 at new Promise (<anonymous>) at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2319:16) at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23) at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)

scenes.0
2024-06-23 13:12:09.579	error	unhandled promise rejection: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed

scenes.0
2024-06-23 13:12:09.579	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

scenes.0
2024-06-23 13:12:09.536	info	starting. Version 3.0.4 in /opt/iobroker/node_modules/iobroker.scenes, node: v20.15.0, js-controller: 5.0.19

scenes.0
2024-06-23 13:12:06.668	info	terminating

scenes.0
2024-06-23 13:12:06.167	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

scenes.0
2024-06-23 13:12:06.166	info	terminating

scenes.0
2024-06-23 13:12:06.166	info	Got terminate signal TERMINATE_YOURSELF
`

Dieses beobachte ich leider schon seit längerem.

**Comment by GermanBluefox** [comment]
Fixed in 3.1.1 please retest
