### ISSUE TITLE
Scenes Adapter Restart Loop

### ISSUE THREAD

**Issue by BendaCoding** [ioBroker/ioBroker.scenes#336]
Seit dem Update des js-controllers auf 5.x, bzw mittlerweile 6.x startet der Scenes Adapter nicht.

**Versions:**  
 - Adapter version: 3.0.4
 - JS-Controller version: 6.0.5
 - Node version: 18.20.3
 - Operating system: Raspbian GNU/Linux 11 (bullseye)

```
2024-06-18 09:07:34.208 | error | instance system.adapter.scenes.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.SchnubbBerry | 2024-06-18 09:07:34.208 | error | Caught by controller[3]: at TCP.<anonymous> (node:net:350:12)
host.SchnubbBerry | 2024-06-18 09:07:34.208 | error | Caught by controller[3]: at Socket.emit (node:domain:489:12)
host.SchnubbBerry | 2024-06-18 09:07:34.207 | error | Caught by controller[3]: at Socket.emit (node:events:517:28)
host.SchnubbBerry | 2024-06-18 09:07:34.207 | error | Caught by controller[3]: at Object.onceWrapper (node:events:632:26)
host.SchnubbBerry | 2024-06-18 09:07:34.207 | error | Caught by controller[3]: at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
host.SchnubbBerry | 2024-06-18 09:07:34.207 | error | Caught by controller[3]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
host.SchnubbBerry | 2024-06-18 09:07:34.207 | error | Caught by controller[3]: Error: DB closed
host.SchnubbBerry | 2024-06-18 09:07:34.207 | error | Caught by controller[2]: at TCP.<anonymous> (node:net:350:12)
host.SchnubbBerry | 2024-06-18 09:07:34.206 | error | Caught by controller[2]: at Socket.emit (node:domain:489:12)
host.SchnubbBerry | 2024-06-18 09:07:34.206 | error | Caught by controller[2]: at Socket.emit (node:events:517:28)
host.SchnubbBerry | 2024-06-18 09:07:34.206 | error | Caught by controller[2]: at Object.onceWrapper (node:events:632:26)
host.SchnubbBerry | 2024-06-18 09:07:34.206 | error | Caught by controller[2]: at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
host.SchnubbBerry | 2024-06-18 09:07:34.206 | error | Caught by controller[2]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
host.SchnubbBerry | 2024-06-18 09:07:34.206 | error | Caught by controller[2]: Error: DB closed
host.SchnubbBerry | 2024-06-18 09:07:34.206 | error | Caught by controller[1]: at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.scenes/main.js:137:9)
host.SchnubbBerry | 2024-06-18 09:07:34.205 | error | Caught by controller[1]: at main (/opt/iobroker/node_modules/iobroker.scenes/main.js:1238:11)
host.SchnubbBerry | 2024-06-18 09:07:34.205 | error | Caught by controller[1]: at initScenes (/opt/iobroker/node_modules/iobroker.scenes/main.js:1171:23)
host.SchnubbBerry | 2024-06-18 09:07:34.205 | error | Caught by controller[1]: at AdapterClass.subscribeForeignStatesAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common-db/src/lib/common/tools.ts:2304:16)
host.SchnubbBerry | 2024-06-18 09:07:34.205 | error | Caught by controller[1]: at new Promise (<anonymous>)
host.SchnubbBerry | 2024-06-18 09:07:34.205 | error | Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/js-controller-common-db/src/lib/common/tools.ts:2307:26
host.SchnubbBerry | 2024-06-18 09:07:34.205 | error | Caught by controller[1]: at AdapterClass.subscribeForeignStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:9749:19)
host.SchnubbBerry | 2024-06-18 09:07:34.204 | error | Caught by controller[1]: at Function.assertPattern (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:252:19)
host.SchnubbBerry | 2024-06-18 09:07:34.204 | error | Caught by controller[1]: Error: Parameter "pattern" needs to be of type "string" or an array of type "string", "function" has been passed
host.SchnubbBerry | 2024-06-18 09:07:34.204 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
scenes.0 | 2024-06-18 09:07:34.071 | error | DB closed
scenes.0 | 2024-06-18 09:07:34.071 | error | Error: DB closed at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:632:26) at Socket.emit (node:events:517:28) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:350:12)
scenes.0 | 2024-06-18 09:07:34.070 | error | uncaught exception: DB closed
scenes.0 | 2024-06-18 09:07:34.056 | error | DB closed
scenes.0 | 2024-06-18 09:07:34.055 | error | Error: DB closed at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:632:26) at Socket.emit (node:events:517:28) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:350:12)
scenes.0 | 2024-06-18 09:07:34.055 | error | uncaught exception: DB closed
scenes.0 | 2024-06-18 09:07:33.874 | info
```

**Comment by Apollon77** [comment]
According to the log the Connection to the iobroker DB was closed, so the adapter could only stop. Please check your system and logs in detail what happened here
