### ISSUE TITLE
Stoppe andere Verzögerungen

### ISSUE THREAD

**Issue by Pmant** [ioBroker/ioBroker.scenes#4]
Wie im Forum besprochen habe ich zwei Szenen gebaut, damit einschalten ohne und ausschalten mit Verzögerung funktioniert. Bei dem Einschaltbefehl wollte ich außerdem "Stoppe andere Verzögerungen", damit beim erneuten Einschalten vor Ablauf des Ausschalttimers dieser gelöscht wird.  Dabei ist mir aufgefallen, dass ein Ändern von "Stoppe andere Verzögerungen" dieser Punkt auch beim selben Gerät in der anderen Szene geändert wird. Außerdem bekam ich dann beim Schalten das hier:
```
host-raspberrypi	2015-08-09 13:32:53	error	instance system.adapter.scenes.0 terminated with code 6 (uncaught exception)
TypeError:	2015-08-09 13:32:53	error	at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
TypeError:	2015-08-09 13:32:53	error	at null._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1867:34)
TypeError:	2015-08-09 13:32:53	error	at Adapter.EventEmitter.emit (events.js:98:17)
TypeError:	2015-08-09 13:32:53	error	at Adapter.id (/opt/iobroker/node_modules/iobroker.scenes/main.js:85:17)
TypeError:	2015-08-09 13:32:53	error	at checkTrigger (/opt/iobroker/node_modules/iobroker.scenes/main.js:265:49)
TypeError:	2015-08-09 13:32:53	error	at activateScene (/opt/iobroker/node_modules/iobroker.scenes/main.js:407:41)
TypeError:	2015-08-09 13:32:53	error	Cannot read property 'val' of undefined
uncaught	2015-08-09 13:32:53	error	exception: Cannot read property 'val' of undefined
TypeError:	2015-08-09 13:32:53	error	at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
TypeError:	2015-08-09 13:32:53	error	at null._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1867:34)
TypeError:	2015-08-09 13:32:53	error	at Adapter.EventEmitter.emit (events.js:98:17)
TypeError:	2015-08-09 13:32:53	error	at Adapter.id (/opt/iobroker/node_modules/iobroker.scenes/main.js:85:17)
TypeError:	2015-08-09 13:32:53	error	at checkTrigger (/opt/iobroker/node_modules/iobroker.scenes/main.js:265:49)
TypeError:	2015-08-09 13:32:53	error	at activateScene (/opt/iobroker/node_modules/iobroker.scenes/main.js:407:41)
TypeError:	2015-08-09 13:32:53	error	Cannot read property 'val' of undefined
uncaught	2015-08-09 13:32:53	error	exception: Cannot read property 'val' of undefined
```

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.scenes/commit/63042511012c42cc20cb6676626ce5f07b96ceba
