### ISSUE TITLE
error on rename scene

### ISSUE THREAD

**Issue by Pmant** [ioBroker/ioBroker.scenes#6]
Beim Umbenennen einer Szene:
```
host-raspberrypi	2015-08-10 22:54:45	error	instance system.adapter.scenes.0 terminated with code 6 (uncaught exception)
TypeError:	2015-08-10 22:54:45	error	at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:291:16)
TypeError:	2015-08-10 22:54:45	error	at Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:247:12)
TypeError:	2015-08-10 22:54:45	error	at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:134:20)
TypeError:	2015-08-10 22:54:45	error	at Decoder. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
TypeError:	2015-08-10 22:54:45	error	at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:301:8)
TypeError:	2015-08-10 22:54:45	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:134:20)
TypeError:	2015-08-10 22:54:45	error	at Manager. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
TypeError:	2015-08-10 22:54:45	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:220:12)
TypeError:	2015-08-10 22:54:45	error	at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:295:6)
TypeError:	2015-08-10 22:54:45	error	at Socket. (/opt/iobroker/node_modules/iobroker.scenes/main.js:436:24)
TypeError:	2015-08-10 22:54:45	error	Cannot read property 'native' of undefined
uncaught	2015-08-10 22:54:45	error	exception: Cannot read property 'native' of undefined
```

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.scenes/commit/9cdea5086efbd3ee5dbd1d1cb2ddbf3a0336a2d5
Erledigt
